#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='chromium gtk-extra'
DESCRIPTION='Installs the Xfce desktop environment. (Approx. 250MB)'
# HOSTBIN='startxfce4'

. "${TARGETSDIR:="$PWD"}/common"

LOCAL_HOSTBIN='startawesome'
LOCAL_CHROOTBIN='startawesome'

# Add a print to the output
echo ''
echo "echo 'Installing target $TARGET...' 1>&2"
# Copy in requested items from host-bin and chroot-bin
for f in $LOCAL_HOSTBIN; do
    echo "Installing $f into the host..." 1>&2
    src="${../host-bin}/$f"
    $SIMULATE cp -fP "$src" "$BIN/"
    [ ! -h "$src" ] && $SIMULATE chmod 755 "$BIN/$f"
done
for f in $LOCAL_CHROOTBIN; do
    echo "Installing $f into the chroot..." 1>&2
    src="${../chroot-bin}/$f"
    $SIMULATE cp -fP "$src" "$CHROOT/usr/local/bin/"
    [ ! -h "$src" ] && $SIMULATE chmod 755 "$CHROOT/usr/local/bin/$f"
done

### Append to prepare.sh:

# Update database
apt-get update

apt-get -y install \
    awesome awesome-extra vim htop `noauto dictionaries-common hddtemp xorg`

TIPS="$TIPS
You can start awesome via the startawesome host command: sudo startawesome
"
