#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='chromium gtk-extra'
DESCRIPTION='Installs the awesome desktop environment.'
LOCAL_HOSTBIN='startawesome'
LOCAL_CHROOTBIN='startawesome'
LOCAL_CHROOTETC='xinitrc'
for f in $LOCAL_HOSTBIN; do
TIPS="$TIPS
    echo "Installing $f into the host..." 1>&2
    src="awesome/host-bin/$f"
    $SIMULATE cp -fP "$src" "$BIN/"
    [ ! -h "$src" ] && $SIMULATE chmod 755 "$BIN/$f"
done
for f in $LOCAL_CHROOTBIN; do
    echo "Installing $f into the chroot..." 1>&2
    src="awesome/chroot-bin/$f"
    $SIMULATE cp -fP "$src" "$CHROOT/usr/local/bin/"
    [ ! -h "$src" ] && $SIMULATE chmod 755 "$CHROOT/usr/local/bin/$f"
done

$SIMULATE mkdir -p "$CHROOT/etc/xdg/awesome"
for f in $LOCAL_CHROOTETC; do
    echo "Installing $f into the chroot /etc..." 1>&2
    src="awesome/chroot-etc/$f"
    $SIMULATE cp -fP "$src" "$CHROOT/etc/xdg/awesome/"
    [ ! -h "$src" ] && $SIMULATE chmod 644 "$CHROOT/etc/xdg/awesome/$f"
done

. "${TARGETSDIR:="$PWD"}/common"


### Append to prepare.sh:

# Update database
apt-get update

apt-get -y install \
    awesome awesome-extra man-db `noauto dictionaries-common hddtemp xorg`

apt-get -y install \
    vim vim-gtk git htop ack autojump zsh zsh-lovers wget ssh

TIPS="$TIPS
You can start awesome via the startawesome host command: sudo startawesome
"
